drop table if exists statistics;

create table if not exists statistics (
    id bigint generated by default as identity not null primary key,
    app varchar(255) not null,
    uri varchar(255) not null,
    ip varchar(15) not null,
    created timestamp;
);