version: '3.1'
services:
  stats-server:
    build: stat-service/server
    image: stats-image
    container_name: stats-server
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - POSTGRES_DB=stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  stats-db:
    image: postgres:13.7-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service
    depends_on:
      - stats-server
      - ewm-db
    ports:
      - "8080:8080"
    environment:
      - STAT_CLIENT_BASEURL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password

  ewm-db:
    image: postgres:13.7-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password